CREATE DATABASE IF NOT EXISTS weatherb_465
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

USE weatherb_465;

CREATE TABLE IF NOT EXISTS User (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    `Password` CHAR(255) NOT NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;
